name: "PDK Update"

on:
  # Run on a schedule to keep the module template up to date...
  schedule:
    - cron: "0 4 * * 1"  # Mondays at 04:00 UTC
  # ...and allow manual runs.
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pdk_update:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_pdk_update.yml@main"
    secrets: "inherit"
