name: Claude PR Review
on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

jobs:
  review:
    if: ${{ !github.event.pull_request.draft }}

    concurrency:
      group: claude-review-pr-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    permissions:
      contents: read
      pull-requests: write
    uses: puppetlabs/cat-github-actions/.github/workflows/claude-pr.yml@main
    secrets:
      anthropic_api_key: ${{ secrets.ANTHROPIC_CODE_REVIEW_KEY }}
      github_token: ${{ secrets.GITHUB_TOKEN }}
