# This is a generic workflow for creating a release prep
# pr for a forge-ruby.
# It requires that the caller sets `secrets: inherit` to ensure
# that secrets are visible from steps in this workflow.
name: "forge-ruby Release Prep"

on:
  workflow_call:
    inputs:
      version:
        description: "forge-ruby version to be released."
        required: true
        type: "string"

jobs:
  release_prep:
    name: "Release prep"
    runs-on: "ubuntu-20.04"

    steps:

      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: "Generate changelog"
        run: |
          export GH_HOST=github.com
          gh extension install chelnak/gh-changelog
          gh changelog new --from-version v5.0.1 --next-version v${{ github.event.inputs.version }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Update version.rb"
        run: |
          current_version=$(grep -o "VERSION = '[^']*'" lib/puppet_forge/version.rb | awk -F"'" '{print $2}' | tr -d \n)
          # Update version in version.rb, only matching first occurrence
          sed -i "0,/$current_version/s//${{ github.event.inputs.version }}/" $(find . -name 'version.rb')
          
      - name: "Get version"
        id: "get_version"
        run: |
          echo "version=$(grep -o "VERSION = '[^']*'" lib/puppet_forge/version.rb | awk -F"'" '{print $2}' | tr -d \n)" >> $GITHUB_OUTPUT

      - name: "Check if a release is necessary"
        id: "check"
        run: |
          git diff --quiet CHANGELOG.md && echo "release=false" >> $GITHUB_OUTPUT || echo "release=true" >> $GITHUB_OUTPUT

      - name: "Commit changes"
        if: ${{ steps.check.outputs.release == 'true' }}
        run: |
          git config --local user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Release prep v${{ steps.get_version.outputs.version }}"

      - name: "Create pull Request"
        uses: "peter-evans/create-pull-request@v5"
        if: ${{ steps.check.outputs.release == 'true' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Release prep v${{ steps.get_version.outputs.version }}"
          branch: "release-prep"
          delete-branch: true
          title: "Release prep v${{ steps.get_version.outputs.version }}"
          base: "main"
          body: |
            Automated release of new version of forge-ruby
          labels: "maintenance"
