---
name: Workflow Restarter
on:
  workflow_call:
    inputs:
      repo:
        description: "GitHub repository name."
        required: true
        type: string
      run_id:
        description: "The ID of the workflow run to rerun."
        required: true
        type: string
      retries:
        description: "The number of times to retry the workflow run."
        required: false
        type: string
        default: "3"

jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check retry count
        id: check-retry
        run: |
          # IF `--attempts` returns a non-zero exit code, then keep retrying
          status_code=$(gh run view ${{ inputs.run_id }} --repo ${{ inputs.repo }} --attempt ${{ inputs.retries }} --json status) || {
              echo "Retry count is within limit"
              echo "should_retry=true" >> $GITHUB_OUTPUT
              exit 0
          }

          # ELSE `--attempts` returns a zero exit code, so stop retrying
          echo "Retry count has reached the limit"
          echo "should_retry=false" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Re-run failed jobs
        if: ${{ steps.check-retry.outputs.should_retry == 'true' }}
        run: gh run rerun --failed ${{ inputs.run_id }} --repo ${{ inputs.repo }}
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
